[versions]
androidxActivity = '1.8.0'
androidxAppcompat = '1.6.1'
androidxArchCore = '2.2.0'
androidxCamera = '1.3.4'
androidxCardview = '1.0.0'
androidxComposeMaterial3 = '1.1.1'
androidxComposeNavigation = '2.7.6'
androidxConstraintlayout = '2.1.4'
androidxConstraintlayoutCompose = '1.0.1'
androidxCore = '1.10.0'
androidxFragment = '1.6.2'
androidxLifecycle = '2.6.2'
androidxPercentLayout = '1.0.0'
androidxPreference = '1.2.0'
androidxRecyclerview = '1.3.0'
androidxSwipeRefreshLayout = '1.1.0'
androidxTest = '1.5.0'
androidxTestEspresso = '3.4.0'
androidxTestExtJunit = '1.1.5'
androidxTestUiAutomator = '2.2.0'
androidxWebkit =  '1.11.0'
androidxWorkManager = "2.9.0"
assertj = '3.23.1'
automatticRest = '1.0.8'
chrisbanesPhotoview = '2.3.0'
dagger = '2.50'
eventBus = '3.3.1'
facebookReact = '0.73.3'
facebookShimmer = '0.5.0'
flipper = '0.247.0'
glide = '4.16.0'
googleFlexbox = '3.0.0'
googleMaterial = '1.9.0'
googleMLKitBarcodeScanning = '17.2.0'
googleMLKitBarcodeScanningCommon = '17.0.0'
googleMLKitTextRecognition = '16.0.0'
googlePlayAppUpdate = '2.1.0'
googlePlayReview = '2.0.1'
googlePlayServicesAuth = '20.4.1'
gson = '2.10.1'
jsoup = '1.16.2'
junit = '4.13.2'
kotlinxCoroutines = '1.7.3'
lottie = '6.1.0'
mockitoAndroid = '4.5.1'
mockitoKotlin = '4.1.0'
screengrab = '2.1.1'
soLoader = '0.10.5'
squareupMockWebServer = '4.12.0'
squareupRetrofit = '2.9.0'
volley = '1.2.1'
wiremock = '2.26.3'
wiremockHttpClient = '4.3.5.1'
wordPressPersistentEditText = '1.0.2'
zendesk = '5.1.2'

[libraries]
android-appUpdate = { group = "com.google.android.play", name = "app-update", version.ref = "googlePlayAppUpdate" }
android-appUpdateKtx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "googlePlayAppUpdate" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidxActivity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "androidxAppcompat" }
androidx-camera = { group = "androidx.camera", name = "camera-camera2", version.ref ="androidxCamera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref ="androidxCamera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref ="androidxCamera" }
androidx-cardView = { group = "androidx.cardview", name = "cardview", version.ref = "androidxCardview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref ="androidxComposeMaterial3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-constraintLayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref ="androidxConstraintlayoutCompose" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-coreCommon = { group = "androidx.arch.core", name = "core-common", version.ref = "androidxArchCore" }
androidx-coreRuntime = { group = "androidx.arch.core", name = "core-runtime", version.ref = "androidxArchCore" }
androidx-coreTesting = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCore" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "androidxFragment"}
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment"}
androidx-lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata-core = { group = "androidx.lifecycle", name = "lifecycle-livedata-core", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }
androidx-percentLayout = { group = "androidx.percentlayout", name = "percentlayout", version.ref = "androidxPercentLayout" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "androidxPreference" }
androidx-recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidxSwipeRefreshLayout" }
androidx-test-espresso-accessibility = { group = "androidx.test.espresso", name = "espresso-accessibility", version.ref ="androidxTestEspresso" }
androidx-test-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref ="androidxTestEspresso" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref ="androidxTestEspresso" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref ="androidxTestExtJunit" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref ="androidxTest" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref ="androidxTest" }
androidx-test-ui-automator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref ="androidxTestUiAutomator" }
androidx-webkit = {group = "androidx.webkit", name = "webkit", version.ref = "androidxWebkit"}
androidx-workManager-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "androidxWorkManager" }
androidx-workManager-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWorkManager" }
androidx-workManager-workTesting = { group = "androidx.work", name = "work-testing", version.ref = "androidxWorkManager" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref ="assertj" }
automattic-rest = { group = "com.automattic", name = "rest", version.ref = "automatticRest" }
chrisbanes-photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref ="chrisbanesPhotoview" }
dagger-android-processor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }
dagger-android-support = { group = "com.google.dagger", name = "dagger-android-support", version.ref = "dagger" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "dagger" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
facebook-flipper = { group = "com.facebook.flipper", name = "flipper", version.ref ="flipper" }
facebook-flipper-network-plugin = { group = "com.facebook.flipper", name = "flipper-network-plugin", version.ref ="flipper" }
facebook-flipper-noop = { group = "com.facebook.flipper", name = "flipper-noop", version.ref ="flipper" }
facebook-react-android = { group = "com.facebook.react", name = "react-android", version.ref ="facebookReact" }
facebook-react-hermesAndroid = { group = "com.facebook.react", name = "hermes-android", version.ref ="facebookReact" }
facebook-shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref ="facebookShimmer" }
facebook-soLoader = { group = "com.facebook.soloader", name = "soloader", version.ref ="soLoader" }
fastlane-screengrab = { group = "tools.fastlane", name = "screengrab", version.ref ="screengrab" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref ="glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref ="glide" }
glide-volley-integration = { group = "com.github.bumptech.glide", name = "volley-integration", version.ref ="glide" }
google-flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "googleFlexbox" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
google-mlkit-barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref ="googleMLKitBarcodeScanning" }
google-mlkit-barcode-scanning-common = { group = "com.google.mlkit", name = "barcode-scanning-common", version.ref ="googleMLKitBarcodeScanningCommon" }
google-mlkit-text-recognition = { group = "com.google.mlkit", name = "text-recognition", version.ref ="googleMLKitTextRecognition" }
google-play-review = { group = "com.google.android.play", name = "review", version.ref ="googlePlayReview" }
google-play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref ="googlePlayReview" }
google-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref ="googlePlayServicesAuth" }
greenrobot-eventBus = { group = "org.greenrobot", name = "eventbus", version.ref ="eventBus" }
greenrobot-eventBus-java = { group = "org.greenrobot", name = "eventbus-java", version.ref ="eventBus" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref ="jsoup" }
junit = { group = "junit", name = "junit", version.ref ="junit" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref ="kotlinxCoroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref ="kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref ="kotlinxCoroutines" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref ="lottie" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref ="lottie" }
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref ="mockitoAndroid" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref ="mockitoKotlin" }
squareup-okhttp-mockWebServer = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref ="squareupMockWebServer" }
squareup-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref ="squareupRetrofit" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
wiremock = { group = "com.github.tomakehurst", name = "wiremock", version.ref ="wiremock" }
wiremock-httpclient-android = { group = "org.apache.httpcomponents", name = "httpclient-android", version.ref ="wiremockHttpClient" }
wordPress-persistentEditText = { group = "org.wordpress", name = "persistentedittext", version.ref = "wordPressPersistentEditText" }
zendesk = { group = "com.zendesk", name = "support", version.ref ="zendesk" }

[plugins]
dagger = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
