[versions]
androidxComposeNavigation = '2.7.6'
androidxWebkit =  '1.11.0'
automatticRest = '1.0.8'
googlePlayAppUpdate = '2.1.0'
wordPressPersistentEditText = '1.0.2'

[libraries]
android-appUpdate = { group = "com.google.android.play", name = "app-update", version.ref = "googlePlayAppUpdate" }
android-appUpdateKtx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "googlePlayAppUpdate" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }
androidx-webkit = {group = "androidx.webkit", name = "webkit", version.ref = "androidxWebkit"}
automattic-rest = { group = "com.automattic", name = "rest", version.ref = "automatticRest" }
wordPress-persistentEditText = { group = "org.wordpress", name = "persistentedittext", version.ref = "wordPressPersistentEditText" }

[plugins]

