# Default Config: https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml

config:
  warningsAsErrors: true

complexity:
  LongParameterList:
    ignoreAnnotated: ['Inject', 'Composable']

formatting:
  android: true
  autoCorrect: false

# See: https://detekt.dev/docs/introduction/compose/
naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

style:
  ForbiddenComment:
    values:
      - 'FIXME:'
      - 'STOPSHIP:'
  MagicNumber:
    ignoreEnums: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
